name: Release

on:
  schedule:
    - cron: "0 8 * * 5"
  push:
    branches:
      - main
      - master

jobs:
  update:
    name: Update version
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install jq
        run: |
          sudo apt-get install -y jq

      - name: Run release.sh script
        id: script
        shell: bash
        run: |
          chmod +x ./release.sh
          ./release.sh

      - name: Commit and push changes
        if: steps.script.outputs.has-changed == 'true'
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update version to support WordPress ${{ steps.script.outputs.tested-up-to }}"
          git push

      - name: Create release
        if: steps.script.outputs.has-changed == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.script.outputs.stable-tag }}
          release_name: Add support for WordPress ${{ steps.script.outputs.tested-up-to }}
          body: Upgrade to WordPress ${{ steps.script.outputs.tested-up-to }}
          draft: false
          prerelease: false

      - name: WordPress Plugin Deploy
        id: deploy
        uses: 10up/action-wordpress-plugin-deploy@2.2.2
        with:
          generate-zip: true
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: simpleanalytics
          VERSION: ${{ steps.script.outputs.stable-tag }}
          ASSETS_DIR: assets

      - name: Upload release asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.deploy.outputs.zip-path }}
          asset_name: ${{ github.event.repository.name }}.zip
          asset_content_type: application/zip
