name: Release

on:
  schedule:
    - cron: "0 8 * * 5"
  push:
    branches:
      - main
      - master

jobs:
  update:
    name: Update version
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install jq
        run: |
          sudo apt-get install -y jq

      - name: Run release.sh script
        id: script
        shell: bash
        run: |
          chmod +x ./release.sh
          ./release.sh

      - name: Commit and push changes
        if: steps.script.outputs.has-changed == 'true'
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update version to support WordPress ${{ steps.script.outputs.tested-up-to }}"
          git push

      - name: Create release
        if: steps.script.outputs.has-changed == 'true'
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.script.outputs.stable-tag }}
          release_name: Add support for WordPress ${{ steps.script.outputs.tested-up-to }}
          body: Upgrade to WordPress ${{ steps.script.outputs.tested-up-to }}
          draft: false
          prerelease: false
